### ISSUE TITLE
NO CODE NO ISSUE :-)

### ISSUE THREAD

**Issue by Ural-Yunusbaev** [dawelab/Ab10-Assembly#1]

**Comment by jl03308** [comment]
Are you talking about the pacbio/nanopore assembly section? The parameters used for Canu and miniasm (one line command) have been stated in the paper.

**Comment by aseetharam** [comment]
Hi @Ural-Yunusbaev! Thanks for checking-in. We are jointly working on the other big NAM project methods section and we will update the repo when we have collected all the information. Meanwhile, if you have questions regarding any section, we will be glad to assist you. Just let us know here what you need!

Thanks,
