### ISSUE TITLE
About Overlap_merge.py

### ISSUE THREAD

**Issue by EugeneKim76** [dawelab/Ab10-Assembly#3]
Dear all

I recently tested scripts in 4-Assembly folder.
However, I failed to run the script 'Overlap_merge.py'.

After running the command below I got error messages
Please help!

Best,
 
python3 /opt/Ab10-Assembly/4-Assembly/Overlap_merge.py \
-x /output/core_assembly/step3_merging/contig_merge/alignref/core_sup_merged_hybridassembly0_CTTAAG_0kb_0labels.xmap \
-k /output/core_assembly/step3_merging/contig_merge/core_sup_merged_hybridassembly0_CTTAAG_0kb_0labels_key.txt \
-o /output/core_assembly/step3_merging/contig_overlap_merge

  File "Overlap_merge.py", line 246, in <module>
    main(xmap_file=args.xmap_file, key_file=args.key_file,out_dir=args.out_dir)
  File "Overlap_merge.py", line 233, in main
    output(overlaps_key_ref_query,out_dir,genomepath)
  File "Overlap_merge.py", line 178, in output
    ref_query=[item for sub in ref_query_all for item in sub if not 'merge' in item]            
  File "Overlap_merge.py", line 178, in <listcomp>
    ref_query=[item for sub in ref_query_all for item in sub if not 'merge' in item]            
TypeError: argument of type 'float' is not iterable

**Comment by jl03308** [comment]
Do you mind attaching your input files here so I can do a test run?

**Comment by EugeneKim76** [comment]
Thanks for Quick reply.
Since my data is not published, I cannot attach my input files.
However, I will show some strange results.
I checked 'overlaps_key' and found that Output_Sequence_ID, Output_Predicted_Len, Query_Sequence_ID_final, Query_Len_final, Ref_Sequence_ID_final, Ref_Len_final were 'NaN' for some Ref1_ID.
I think that is the reason for the error 'TypeError: argument of type 'float' is not iterable'
How can I solve the problem?

**Comment by jl03308** [comment]
I see. Have you inspected your hybrid assembly after contig merging with BionanoSolve? Or did you look at the gap file to check the presence of 13N gaps? Is it possible that you don't have contig overlaps? Sharing the files will definitely help me to resolve this issue faster, you could directly send the files to my email instead of attaching them here, if you're comfortable with it.

**Comment by EugeneKim76** [comment]
Dear jl03308
I think I had better discuss about sharing the data.
If permission is granted I will send you, however, I'm not sure if I can get permission.
Hence,  if possible, I hope that the problem is solved through discussion.

First,
I checked Hybrid Scaffolds and found 13Ns gaps.

Second,
Here, I will show you an example of 'overlap_key' (which is similar to my result)
As shown below, cluster 3, 12 are 'overlaps_key_cluster.shape[0] > 1'.
'Output_Sequence_ID' with such cluster showed 'NaN'.
I guess the problem can be solved by fixing line 120 (overlaps_key_cluster = overlaps_key[overlaps_key['cluster']==4])

  Ref1_ID... cluster
0      2     ...  0
1      6     ...  1
2      6     ...  2
3      7     ...  3
4      7     ...  3
5      7     ...  3
6      7     ...  3
7      9     ...  4
8      12     ...  5
9      13     ...  6
10    15    ... 7
11    16    ...  8
12    18    ...  9
13    19    ...  10
14    19    ...  11
15    20    ...  12
16    21    ...  12
17    24    ...  13

**Comment by EugeneKim76** [comment]
Dear all,
I guess previous version is for overlaps with cluster 4 which is overlaps_key_cluster.shape[0] > 1.
Hence, I suggest fix Overlap_merge.py as shown below, for general case. (overlaps with clusters which are overlaps_key_cluster.shape[0] > 1)
I found Overlap_merge.py works well without errors after correction.
However, I want to know whether the corrected version is wrong.
Would you test my corrected version?
Best,
[Overlap_merge.txt](https://github.com/dawelab/Ab10-Assembly/files/6349696/Overlap_merge.txt)



line 120        
overlaps_key_cluster = overlaps_key[overlaps_key['cluster']==4]
-> fixed
 #overlaps_key_cluster = overlaps_key[overlaps_key['cluster']==4]

line 132, 133
            for i in overlaps_key_cluster.index[1:]:
                overlaps_key.loc[i,'Output_Sequence_ID'] = overlaps_key.loc[i-1,'Output_Sequence_ID'].split('_map')[0] +'_merge'+ str(i+1) +'_map' + str(overlaps_key.loc[i,'Ref1_ID'])
->add overlaps_key_cluster = overlaps_key[overlaps_key['cluster']==x] between 132 and 133
            for i in overlaps_key_cluster.index[1:]:
                overlaps_key_cluster = overlaps_key[overlaps_key['cluster']==x]
                overlaps_key.loc[i,'Output_Sequence_ID'] = overlaps_key.loc[i-1,'Output_Sequence_ID'].split('_map')[0] +'_merge'+ str(i+1) +'_map' + str(overlaps_key.loc[i,'Ref1_ID'])

line 216
item_path = os.path.join(out_dir,overlap_sequence_ids,item+'.fasta')
->fixed
item_path = os.path.join(out_dir,'*',item+'.renamed.fasta')

**Comment by jl03308** [comment]
Okay! I'll let you know once I finish the test.

**Comment by EugeneKim76** [comment]
Dear jl03308
I tested another assemblies and found a case that needs 'overlaps table' sorting (by index).
Hence, I suggest fix Overlap_merge.py in addition to mentioned above issue.

line 89-91 
               overlaps.loc[i,'Orientation_final'] = "-"
    return overlaps
->fixed
                   overlaps.loc[i,'Orientation_final'] = "-"
    overlaps=overlaps.sort_index()
    return overlaps


Here, I attached corrected version.
Please test this file (new correction is added to above attached file) 
[Overlap_merge_ver.2.txt](https://github.com/dawelab/Ab10-Assembly/files/6369566/Overlap_merge_ver.2.txt)

Best,

**Comment by jl03308** [comment]
Yes, that works perfectly. Thanks!

**Comment by EugeneKim76** [comment]
Dear all

I recently tested updated scripts in 4-Assembly folder.
However, I failed to run the script 'Overlap_merge.py'.
After running the command below I got error messages.

python3 /opt/Ab10-Assembly/4-Assembly/Overlap_merge.py
-x /output/core_assembly/step3_merging/contig_merge/alignref/core_sup_merged_hybridassembly0_CTTAAG_0kb_0labels.xmap
-k /output/core_assembly/step3_merging/contig_merge/core_sup_merged_hybridassembly0_CTTAAG_0kb_0labels_key.txt
-o /output/core_assembly/step3_merging/contig_overlap_merge

Hence, I suggest fix Overlap_merge.py as shown below.

line 69
return overlaps.sort_values('Ref1_ID').drop_duplicates(subset=['Query1_ID', 'Query2_ID'], keep='first')
->   
return overlaps.sort_values('Ref1_ID').drop_duplicates(subset=['Query1_ID', 'Query2_ID'], keep='first').sort_index().reset_index(drop=True)

line 131-132
            overlaps_key.loc[i,'Ref_Len_final'] = overlaps_key_cluster.loc[i,'Ref_Len']	
            for i in overlaps_key_cluster.index[1:]:	
->
            overlaps_key.loc[i,'Ref_Len_final'] = overlaps_key_cluster.loc[i,'Ref_Len']
            overlaps_key_cluster = overlaps_key[overlaps_key['cluster']==x]    
            for i in overlaps_key_cluster.index[1:]:
                overlaps_key_cluster = overlaps_key[overlaps_key['cluster']==x]

line 216
 item_path = os.path.join(out_dir,overlap_sequence_ids,item+'.fasta')
->
 item_path = os.path.join(out_dir,'*',item+'.renamed.fasta')

I found Overlap_merge.py works well without errors after correction.
However, I want to know whether the corrected version is wrong.
Would you test my corrected version?
Here, I attached corrected version.
Please test this file
[Overlap_merge_3rd.txt](https://github.com/dawelab/Ab10-Assembly/files/7852344/Overlap_merge_3rd.txt)

Best,



P.S I got error messages as shown below

Traceback (most recent call last):
  File "/root/anaconda3/envs/Biopython_1.71/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1032, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1039, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 10

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/Ab10-Assembly/4-Assembly/Overlap_merge_ver.2.py", line 246, in <module>
    main(xmap_file=args.xmap_file, key_file=args.key_file,out_dir=args.out_dir)
  File "/opt/Ab10-Assembly/4-Assembly/Overlap_merge_ver.2.py", line 230, in main
    overlaps_key=group(overlaps_key)
  File "/opt/Ab10-Assembly/4-Assembly/Overlap_merge_ver.2.py", line 98, in group
    if overlaps_key.loc[i,'Ref1_ID'] == overlaps_key.loc[i-1,'Ref1_ID'] and overlaps_key.loc[i,'R1_Start'] <= overlaps_key.loc[i-1,'R1_End']:
  File "/root/anaconda3/envs/Biopython_1.71/lib/python3.6/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/root/anaconda3/envs/Biopython_1.71/lib/python3.6/site-packages/pandas/core/indexing.py", line 1044, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/root/anaconda3/envs/Biopython_1.71/lib/python3.6/site-packages/pandas/core/indexing.py", line 786, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/root/anaconda3/envs/Biopython_1.71/lib/python3.6/site-packages/pandas/core/indexing.py", line 1110, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/root/anaconda3/envs/Biopython_1.71/lib/python3.6/site-packages/pandas/core/indexing.py", line 1059, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/root/anaconda3/envs/Biopython_1.71/lib/python3.6/site-packages/pandas/core/generic.py", line 3493, in xs
    loc = self.index.get_loc(key)
  File "/root/anaconda3/envs/Biopython_1.71/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 10
